import "@/app/globals.scss"
import Providers from "@/components/Provider"
import CursorFollower from "@/components/UI/Atoms/CursorFollower"
import { TCanvas } from "@/components/three/TCanvas"
import type { Metadata } from "next"
import { Oswald, Overpass, Playfair_Display } from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const overpass = Overpass({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-overpass",
})
const oswald = Oswald({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-oswald",
})
const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${oswald.variable}  ${oswald.className} ${overpass.variable}  ${overpass.className} ${playfair.variable}  ${playfair.className} relative`}
    >
      <body className={overpass.className}>
        <Providers>
          <CursorFollower />
          {/* <Header /> */}
          <aside className="absolute top-0 left-0 w-full h-full z-10">
            <TCanvas />
          </aside>
          {children}
          {/* <Footer /> */}
        </Providers>
      </body>
    </html>
  )
}
