import type { Metadata } from "next"
import { Inter, Jost } from "next/font/google"
import "./globals.scss"
import BasicHeader from "@/components/UI/Global/Headers/BasicHeader"
import BasicFooter from "@/components/UI/Global/Footers/BasicFooter"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-jost",
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${jost.variable}  ${jost.className}`}>
      <body className={inter.className}>
        <BasicHeader />
        {children}
        <BasicFooter />
      </body>
    </html>
  )
}
